.github/PULL_REQUEST_TEMPLATE.md, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/PrintSuppliers.java, src/main/resources/application.yml, ui/package-lock.json, ui/src/CollectionExerciseDetails.js
Why?
The print supplier field in the support tool was previously a free text box, this is not a good idea.
What?
The support tool backend now has a config item in application.yml specifying print suppliers and a new endpoint to serve these up.
The support tool frontend now gives the choice of print supplier to use, retrieved from the aforementioned print supplier endpoint.
How to test?
Run the frontend and backend on this branch:
create a survey
create a collection exercise
create wave of contact - the print supplier should now display as a dropdown giving the options that are in the print supplier config in the backend.
Links?
https://trello.com/c/6tMnh7n3/2388-limit-print-suppliers-in-ui-based-on-print-file-service-config-8
=> Limit print suppliers

src/main/java/uk/gov/ons/ssdc/supporttool/model/entity/User.java
`user` is a reserved word in SQL. Causes problems with DDL and stuff.
Changed user table to be called users... same solution as with cases table.
Start everything. Does it work?
Trello: https://trello.com/c/EJIfiW4G
=> Fix user reserved word

ui/src/App.js, ui/src/CaseDetails.js, ui/src/CaseSearch.js
The case details popup didn't show any event history or UAC/QIDs.
Created case details page which shows event history & UAC/QIDs.
Load a sample. Run the UI using `make run-dev-ui` and go to http://localhost:3000 then search for a case and open the details.
Trello: https://trello.com/c/7yGpUzcW
=> Case details page - detailed version

src/main/java/uk/gov/ons/ssdc/supporttool/model/entity/Job.java
Performance was bad, when testing with a 450k sample.
Removed the `cascade = CascadeType.ALL` from the JobRows, so that Hibernate wouldn't have to figure out if we had fiddled with any of the rows, every time we update the Job progress.
Load a 450k sample. Profit.
Trello: https://trello.com/c/0eA4YuSI
=> Fix performance issue with massive samples

src/main/java/uk/gov/ons/ssdc/supporttool/model/entity/Event.java
When the Spring auto-generated CRUD API attempts to gather all the data about events, it tries to follow all links, and in so doing it ends up in an infinite loop, which eventually causes a stack overflow.
Told Jackson to ignore one end of the bidirectional relationship between events and cases/uac-qid-links.
Load a sample. Send in a few different types of event (receipt, refusal, deactivate UAC etc) and then use the case search feature in the UI to view the case - it should work; not fail.
Trello: https://trello.com/c/3gYzhczr
=> Fix CRUD REST API crashing due to stack overflow

pom.xml, src/main/resources/application.yml
We were running on a version of Spring Boot from May 2020.
Upgraded to the latest and greatest Spring Boot.
Run the ATs. Should be zero regression.
Trello: https://trello.com/c/8MZx3DE9
=> Upgrade to Spring Boot v2.5.2 / Data REST v3.5.3-SNAPSHOT

src/main/java/uk/gov/ons/ssdc/supporttool/service/CaseService.java, src/main/resources/application.yml
Routing key != queue name. If you want to send directly to a queue, use the default exchange. Otherwise, use the `events` exchange with a meaningful routing key.
Named the routing keys better.
Run the ATs. Should be zero regression.
Trello: https://trello.com/c/4CgML4w6
=> Make routing keys consistent

src/main/java/uk/gov/ons/ssdc/supporttool/model/entity/EventType.java
CASE_CREATED & UAC_UPDATED are unused (database) event types.
SAMPLE_LOADED is misleading, because it does not tell us when a sample was loaded, but in fact when we received an instruction to create a case.
We should get rid of SAMPLE_LOADED and UAC_UPDATED and store a CASE_CREATED when we create a case.
Removal of bad events
Build images and run ATs
https://trello.com/c/JnLxj02F
=> Removal of Bad Events

src/main/java/uk/gov/ons/ssdc/supporttool/security/UserIdentity.java, src/main/resources/application.yml
Currently, when testing via Docker Dev on a local machine, the identity is faked as `dummy@fake-email.com` which is also granted super user permission, by default.
We need a mechanism to fake different user identities, so that we can test that RBAC is working.
Created environment variable called `DUMMY_USER` in the `.env` file in docker dev. This can be changed to fake any email you want, but you will need to ensure the user is present in the `users` table in the database and has been granted permissions via group membership etc.
Change the user to anything other than `dummy@fake-email.com` and then set it up in the DB with some permissions, and you should see RBAC working locally.
Trello: https://trello.com/c/oO5I3bIz
=> Make it easier to test RBAC

src/main/java/uk/gov/ons/ssdc/supporttool/security/UserIdentity.java, src/main/java/uk/gov/ons/ssdc/supporttool/validation/MandatoryRule.java
Spring Boot 2.5.2 deprecates StringUtils.isEmpty.
Used `StringUtils.hasText` instead.
Zero regression.
Trello: https://trello.com/c/f7yh1qjL
=> Replace deprecated StringUtils.isEmpty with hasText

src/main/java/uk/gov/ons/ssdc/supporttool/schedule/FileStager.java, src/main/java/uk/gov/ons/ssdc/supporttool/schedule/RowStager.java
Uploaded sample files fill up the `/tmp` directory because they're not cleaned up.
Clean up files when we're done with them.
Upload a bunch of sample files and check that the /tmp directory files are deleted.
Trello: https://trello.com/c/oi6VFzJE
=> Spike delete uploaded sample files when done

src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/FileUploadEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/schedule/FileStager.java, src/main/java/uk/gov/ons/ssdc/supporttool/schedule/RowStager.java, src/main/resources/application.yml
The file storage was hardcoded to use `/tmp/`, this is fine locally but when running in the cloud we need to be able to point it to a persisted directory.
- Replace hardcoded paths with config variable
Eyeball and run tests with `mvn`
https://trello.com/c/0T29EVaG/2541-work-out-realistic-infrastructure-size-for-performance-testing-eg-db-disk-rabbit-mq-memory-etc-1-day
=> Make file upload storage directory configurable

src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/FileUploadEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/JobEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/security/UserIdentityInterceptor.java, ui/src/SampleUpload.js
When loading a massive sample or on a slow connection and the sample load takes more than 10 minutes, the JWT token times out and the load fails.
The sample load and the insertion of the job has been split into two endpoints. 
The identity isn't checked when the upload endpoint is called.
The existing `/api/job` endpoint now has a POST endpoint to create the job details.
The frontend calls both endpoints as part of the sample upload process.
- Build the image and run in docker. `make test` on the acceptance tests [branch of the same name](https://github.com/ONSdigital/ssdc-rm-acceptance-tests/pull/28) to test there is no regression.
- Tag and push the docker image to your GCP env and deploy it.
- Load a sample. This should be a big sample that takes over 10 minutes to load. The chrome dev …
=> Fix massive sample load failure

src/main/java/uk/gov/ons/ssdc/supporttool/Application.java, src/main/java/uk/gov/ons/ssdc/supporttool/config/AppConfig.java, src/main/java/uk/gov/ons/ssdc/supporttool/config/OurProjectPubsubConfig.java, src/main/java/uk/gov/ons/ssdc/supporttool/config/SharedProjectPubsubConfig.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/DeactivateUacEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/schedule/RowChunkProcessor.java, src/main/java/uk/gov/ons/ssdc/supporttool/service/CaseService.java, src/main/resources/application.yml, src/test/resources/application-test.yml
RM doesn't 'own' the topics and subscriptions which are used to integrate between other products... and as such, they should be kept in a shared project.
Use our own project only for internal messaging, otherwise use a shared project.
Build Case Processor and Support Tool, then start everything up in docker dev with `make up` and then run the acceptance tests with `make test`... should be zero regression.
Trello: https://trello.com/c/yPZ72ten
=> Use shared project for shared pubsub topics and subscriptions

src/main/resources/application.yml
Case processor is refusing to start up in GCP.
Added pubsub emulator config to disable emulator.
Try it.
Trello: https://trello.com/c/yPZ72ten
=> Fix pusbub emulator host required problem

src/main/java/uk/gov/ons/ssdc/supporttool/config/OurProjectPubsubConfig.java, src/main/java/uk/gov/ons/ssdc/supporttool/config/SharedProjectPubsubConfig.java
For some unknown reason, Spring is spitting its dummy about `GcpPubSubProperties` when in GCP.
Removed need for `GcpPubSubProperties` class.
Try it.
Trello: https://trello.com/c/yPZ72ten
=> Remove dependency on GcpPubSubProperties

src/main/java/uk/gov/ons/ssdc/supporttool/config/PubsubTransportConfig.java
The Google PubSub libraries are acting differently in GCP versus what they are on local machine, with the emulator.
Added config that was missing.
Try it.
Trello: https://trello.com/c/yPZ72ten
=> Add auto pubsub config that was missing for GCP

src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/messaging/Sample.java, src/main/java/uk/gov/ons/ssdc/supporttool/transformer/SampleTransformer.java
Correlation IDs are incredibly useful for audit trail, digital forensics, debugging and diagnosing defects, "identifying training opportunities" and suchlike. They only work if they truly correlate related events together, end-to-end.
Likewise, having an audit trail of the originating user - where it's known - is useful too, and saves a lot of hassle trawling through load balancer logs, trying to figure out who initiated a particular chain of events.
Preserved the correlation ID and originating user, where it's known, across events and other cascading effects from the original cause.
Use the support tool to create various types of event (e.g. refusal, receipt etc) and check that the resulting case and UAC updates have the correlation ID on them, and originating user (where appropriate). …
=> Preserve correlation ID and originating user across events

ui/src/LandingPage.js
Understanding time zone complexities is not easy. Intuitively, it might seem 'obvious' that all times in a user interface should be in 'local' time, but that's not true: when you are talking about a time in the future, you might be talking about a time in a different time zone than the the current local time zone, because of daylight saving.
Consider this particularly awful problem: setting the trigger date and time to 1:30am 27 March 2022, when should this trigger run? 1:30am GMT? That makes no sense because at 1am on 27 March 2022, the clocks spring forward to 2am... therefore 1:30am on that day does not exist!
Changed the fulfilment trigger dialog to display and use the time according to the user's local clock... currently BST as of 8th September 2021. When daylight saving ends, the UI …
=> Fix UTC/BST time mixup, for fulfilment triggers

src/main/java/uk/gov/ons/ssdc/supporttool/client/ExceptionManagerClient.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ExceptionManager.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/messaging/SkipMessageRequest.java
We want an audit trail of who quarantined messages.
Did a best attempt at linking the user who originally requested that a message be 'skipped' to the eventual implementation of that request by the Exception Manager. User is recorded in a `skipping_user` database column in the `quarantined_message` table.
Create a bad message, either using the docker dev `publish_message.sh` script locally, or by publishing directly to a topic in GCP. Then, use the support tool to skip a message. Also, try skipping a message using the toolbox bad message wizard. Check the database - it should have recorded the user who skipped the message!
Trello: https://trello.com/c/JNPHZeos
=> Record user who quarantined message for audit trail

ui/src/GroupDetails.js, ui/src/UserDetails.js
We need the ability to revoke permissions from groups and group permissions from users
User details screen: Each permission has a remove button next to it.  When you click it, you'll be asked to confirm before the permission is removed.
Group details screen: Each permission has a remove button next to it.  When you click it, you'll be asked to confirm before the permission is removed.
Add some activity permissions into a group.  Click the remove button to remove it.
Add some group permissions to a user.  Click the remove button to remove the group.
You should be given the chance to back out before any permissions are removed.
https://trello.com/c/J7WZc0IL
=> Revoke activity permissions and remove users from groups

pom.xml, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ActionRuleEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/CaseEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/messaging/ActionRuleDTO.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/repository/ActionRuleRepository.java, ui/src/CollectionExerciseDetails.js
Need to add createdBy column to action_rule table to be able to keep an audit trail
New endpoint for posting action rules into database
New ActionRuleDTO
Updated CollectionExerciseDetails.js
Check the db for the createdBy column and check you can create an action rule
https://trello.com/c/m26JBFvw
=> Add createdBy Column to Action Rule Table

pom.xml, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ActionRuleEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ActionRuleSurveyPrintTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ActionRuleSurveySmsTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/FulfilmentSurveyPrintTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/messaging/ActionRuleDTO.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/messaging/AllowTemplateOnSurvey.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/repository/ActionRuleSurveySmsTemplateRepository.java, src/main/java/uk/gov/ons/ssdc/supporttool/utility/AllowTemplateOnSurveyValidator.java, src/main/java/uk/gov/ons/ssdc/supporttool/utility/SampleColumnHelper.java, ui/src/CollectionExerciseDetails.js, ui/src/LandingPage.js, ui/src/PrintFulfilment.js, ui/src/SensitiveData.js, ui/src/SmsFulfilment.js, ui/src/SurveyDetails.js, ui/src/Utils.js
To run SMS action rules we need the Case Processor to send SMSs driven by action rules.
Allowed action rules to send SMSs.
Check out and build the linking DDL branch to build the required common entities snapshot.
Check out and build the other linked service branches
Check out and run the linked docker dev branch
Check out and run the linked ATs branch
https://trello.com/c/LvFNl7N6/2851-sis2-enable-action-rules-to-send-sms-messages-21
=> Allow Action Rule to have SMS template and phone number column on it

pom.xml, src/test/resources/example-validator-config.json
We are planning on using a CSV sample load as a tactical solution for SIS2 wave one. This sample file will contain phone numbers, which we will need a way of validating.
Added regex validation.
Set up a survey with a column validation rule like this...
```json
{
"columnName": "PHONE_NUMBER",
"sensitive": true,
"rules": [
{
"className": "uk.gov.ons.ssdc.common.validation.RegexRule",
"expression": "^07[0-9]{9}$"
}
]
}
```
Then, try loading a sample with dodgy phone numbers.
Trello: https://trello.com/c/PW2rRdlL
=> Add regex rule for phone numbers

src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ActionRuleSurveyPrintTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/DeactivateUacEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/PrintSuppliersEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/SmsTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/UserEndpoint.java, src/test/java/uk/gov/ons/ssdc/supporttool/endpoint/AllEndpointsIT.java, src/test/java/uk/gov/ons/ssdc/supporttool/testhelper/BundleOfUsefulTestStuff.java, src/test/java/uk/gov/ons/ssdc/supporttool/testhelper/BundlePostObjectGetter.java, src/test/java/uk/gov/ons/ssdc/supporttool/testhelper/BundleUrlGetter.java, src/test/java/uk/gov/ons/ssdc/supporttool/testhelper/IntegrationTestHelper.java
There are almost 70 RESTful API endpoints which are required for the Support Tool to work. We should test them... at least to check that the security is working for all of them.
Built a mechanism to check that all the endpoints are protected by role-based access control (RBAC) and then used that to check almost all the endpoints.
Build the project... it will automatically test all the endpoints.
Trello: https://trello.com/c/3us6jDjj
=> Integration test [almost] all the endpoints

ui/src/LandingPage.js
It's useful to know which template an SMS template is using, at the Gov Notify end of business.
Displayed the ID in the UI.
Try it.
Trello: https://trello.com/c/gdpVHBKS
=> Add Gov Notify Template ID to UI

ui/src/CaseDetails.js, ui/src/CollectionExerciseDetails.js, ui/src/ExceptionManager.js, ui/src/GroupDetails.js, ui/src/LandingPage.js, ui/src/PrintFulfilment.js, ui/src/SensitiveData.js, ui/src/SmsFulfilment.js, ui/src/SurveyCaseSearch.js, ui/src/SurveyDetails.js, ui/src/SurveySampleSearch.js, ui/src/UserAdmin.js, ui/src/UserDetails.js, ui/src/Utils.js
There are two parts to securing a single-page application: 1. Don't display parts of the UI which the user isn't authorised to see, and 2. Don't call APIs which the user isn't authorised to use. We were doing the first, but not the second.
Added checks to make sure user is authorised before calling all APIs.
Try accessing the UI with the reduced permissions and check that it doesn't crash anywhere, now that it's not going to the backend for a bunch of data.
Trello: https://trello.com/c/HhliKdR2
=> Don't call APIs if not authorised to do so

pom.xml, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/JobEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/ui/JobDto.java, src/main/java/uk/gov/ons/ssdc/supporttool/security/UserIdentity.java, src/main/java/uk/gov/ons/ssdc/supporttool/transformer/NewCaseTransformer.java, ui/src/JobDetails.js
Support Tool user who clicked "Process" sample button should be originating user of newCase events
New case events have the user who pressed process as the originating user.
Job details pop up will say who either processed it or cancelled the job.
To check the processed by stuff:
1. Build the image and `make up` in docker dev
2. Stop the case processor in docker dev (`docker stop caseprocessor`)
3. Load a sample, let it validate but don't process immediately.
4. Change the user you're working as.
5. Process the sample file
6. Check the user you're acting as and the time you clicked process show up on the job details window
7. In the docker dev repo ` ./get_message.sh event_new-case_rm-case-processor shared-project` and check the originating user in the JSON is the user you changed to to …
=> Originating user for new case events are the person who clicked process

src/main/java/uk/gov/ons/ssdc/supporttool/schedule/RowChunkProcessor.java, src/main/java/uk/gov/ons/ssdc/supporttool/transformer/NewCaseTransformer.java, src/main/java/uk/gov/ons/ssdc/supporttool/transformer/Transformer.java
If the support tool backend is rebooted during a sample load, it will resend any of the cases in the batch it was in the middle of processing, which will create some dupes (between 1 and 500).
If we use the job row ID as the case ID then any dupes will be rejected, because Case Processor checks to see if the case ID exists before storing the case.
Load a sample. If you wanna get fancy, load a sample and restart the support tool while it's processing, then check that there are no extra cases created.
Trello: https://trello.com/c/Fcg2cl2b
=> Use job row ID for case ID instead of random ID

.travis.yml, Makefile, ui/Makefile, ui/package-lock.json, ui/package.json
We should be checking package safety in PR reviews
- Add npm audit make targets
- Add audit check to travis build
- npm audit fix for automatic dependency fixes
- Move react-scripts to dev dependencies as it is a build tool and cannot currently pass npm audit
Check the travis build is running the audit.
https://trello.com/c/1IgWzUCI/2889-productionize-support-tool-fix-js-vulnerabilities-and-warn-on-them-in-future-5
=> 2889 Add npm package audit check

pom.xml, ui/src/CollectionExerciseDetails.js, ui/src/LandingPage.js, ui/src/SampleUpload.js, ui/src/SurveyDetails.js
It's hard to use the UI if you're not a super user.
Added table headings.
Try it as a non-super-user (e.g. with RM SUPPORT group)
Trello: https://trello.com/c/4b22QCDM
=> Add table headings to improve UI for non-superusers

pom.xml, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/UserGroupEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/UserGroupMemberEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/UserGroupPermissionEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/repository/UserGroupRepository.java, src/test/java/uk/gov/ons/ssdc/supporttool/endpoint/AllEndpointsIT.java, src/test/java/uk/gov/ons/ssdc/supporttool/testhelper/BundleOfUsefulTestStuff.java, src/test/java/uk/gov/ons/ssdc/supporttool/testhelper/IntegrationTestHelper.java, ui/src/GroupDetails.js, ui/src/UserAdmin.js, ui/src/UserDetails.js
Neither the UI nor back end should allow duplicate permissions, groups or memberships. 
- Block duplicate groups, permissions and memberships in back end
- Block duplicate groups, permissions and memberships in front end
Try to create duplicate groups, permissions or memberships either with the UI or API directly.
https://trello.com/c/uMBMYfs8/2787-support-tool-duplicate-permissions
=> 2787 Protect against duplicate groups and permissions

src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/UserEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/UserGroupAdminEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/UserGroupEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/UserGroupMemberEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/ui/UserGroupAdminDto.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/repository/UserGroupAdminRepository.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/repository/UserGroupMemberRepository.java, src/test/java/uk/gov/ons/ssdc/supporttool/endpoint/AllEndpointsIT.java, src/test/java/uk/gov/ons/ssdc/supporttool/testhelper/BundleOfUsefulTestStuff.java, src/test/java/uk/gov/ons/ssdc/supporttool/testhelper/IntegrationTestHelper.java, ui/package-lock.json, ui/package.json, ui/src/App.js, ui/src/GroupDetails.js, ui/src/LandingPage.js, ui/src/MyGroupUserAdmin.js, ui/src/MyGroupsAdmin.js, ui/src/UserAdmin.js, ui/src/UserDetails.js
Only allowing super users to administer users is not a good security model
Users can be made "group admin" (by a super user) which allows them to add and remove users from the group that they are admin of.
Try it!
Trello: https://trello.com/c/wOVQ3NxV
=> Allow group admins to add and remove users

ui/src/BulkUploads.js, ui/src/SampleUpload.js
Tables were incorrectly using the upload job created date as the table key.
Tables now use index as the key.
Upload some files and check it all displays correctly
https://trello.com/c/MGxzLrQI/3050-support-tool-ui-use-unique-index-identifier-for-table-rows-in-sample-and-bulk-uploads
=> Use index as key for upload rows

ui/src/CaseDetails.js, ui/src/EmailFulfilment.js, ui/src/ExceptionManager.js, ui/src/SmsFulfilment.js
There are bugs when entering a mobile number and email address for a fulfilment, which is rejected by the server because it fails validation... subsequent clicks of the button don't work because of double-click protection not being reset.
Also, there is no double-click protection when deactivating UACs.
Fixed the bugs.
Try it.
Trello: https://trello.com/c/6T8XqWkj
=> Fix double click bugs

src/main/java/uk/gov/ons/ssdc/supporttool/validators/CaseExistsInCollectionExerciseRule.java, src/test/java/uk/gov/ons/ssdc/supporttool/validators/CaseExistsInCollectionExerciseRuleTest.java
The bulk processor would fail at runtime if the `CaseExistsInCollectionExerciseRule` was given an invalid format UUID.
- Handle errors in UUID from string in `CaseExistsInCollectionExerciseRule`
- Add tests
Try bulk processing a file with an invalid format case ID. It should now be reported as a standard validation failure, not cause unhandled errors.
https://trello.com/c/SiYRKz0w/3075-bulk-processor-crashes-handle-non-uuid-values-in-case-id-validator
=> 3075 Handle errors in string to UUID conversion in case ID rule

.travis.yml
our travis builds are failing often due to dockerhub rate limiting failures, to solve this we need to log into an dockerhub enterprise account
- added a second docker login command line into .travis to use a enterprise dockerhub account
- trigger tests in travis and make sure it doesn't fail
=> added a second docker login command to travis config

src/main/java/uk/gov/ons/ssdc/supporttool/utility/Constants.java
We have released `0.5.0` of the [shared events](https://github.com/ONSdigital/ssdc-shared-events) so it's time to bring our microservices in line with that spec.
Changed all the microservices to publish `0.5.0` as the event version in the headers, and do a few other tweaks to meet the specification.
Also, allow some more versions to be sent to us for present and future needs.
Zero regression - ATs should pass.
Trello: https://trello.com/c/9uTTLrLW
=> Migrate to shared events version 0.5.0 release

pom.xml, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/CollectionExerciseEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/ui/CollectionExerciseDto.java, src/test/java/uk/gov/ons/ssdc/supporttool/endpoint/AllEndpointsIT.java, src/test/java/uk/gov/ons/ssdc/supporttool/endpoint/CollectionExerciseEndpointIT.java, src/test/java/uk/gov/ons/ssdc/supporttool/endpoint/CollectionExerciseEndpointTest.java, src/test/java/uk/gov/ons/ssdc/supporttool/testhelper/IntegrationTestHelper.java, ui/src/SurveyDetails.js
Choosing the correct collection instrument (CI) for a respondent needs to be rules-based, because there are myriad known and unknown requirements that the ONS has, regarding which questionnaire the organisation wants a respondent to fill in.
Allowed a block of rules for choosing a collection instrument to be stored against a collection exercise, and these rules are then used to choose the right CI at the moment when the action rule runs.
This has been performance tested with 10k cases, which took 3 minutes to produce the print file = 55/second... pretty slow. but this was on my local MacBook running with the Pub/Sub emulator, and in debug mode. It should scale horizontally, and besides, we need to know what the performance was before for a like-for-like comparison.
We could try choosing …
=> Collection Instrument Rules

.travis.yml, Dockerfile, pom.xml, src/main/resources/application.yml
Java 11 is no longer the LTS (Long-Term Support) version. Java 17 is the LTS version, so we should use that.
Spring Boot 2.6.0 is the first version of Spring Boot to support Java 17, so we should use that too.
Upgraded to Java 17 and Spring Boot 2.6.0, plus upped any other versions required for everything to work.
Switched the Docker base image over to be JDK 17 too.
Zero regression.
Trello: https://trello.com/c/kcJGECdH
=> Upgrade to Java 17 and Spring Boot 2.6.0

ui/src/SurveyDetails.js
The handler function was missing, meaning the "Allow SMS Template On Action Rule" submit button simply didn't work.
- Add missing handler to UI
Try allowing an SMS template for action rules on a survey
https://trello.com/c/JIjNalrX/3139-defect-allow-sms-template-on-action-rules-has-no-submit-button-handler
=> Fix missing handler for allow SMS template on action rule

pom.xml, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/AuthorisationEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/AuthorisedActivityTypesEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/UserGroupPermissionEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/security/UserIdentity.java, ui/src/GroupDetails.js
Global permissions need to be handled differently from survey-specific permissions. For example, being able to see the list of SMS templates is not something survey specific. As such, it's hard for our UI to know what APIs are allowed to be called.
To solve this problem, by marking global permissions as global, we can filter those permissions out when the user is a super user on a specific survey, so it doesn't confuse the UI.
Added `global` flag to permissions. Filtered out the global permissions for survey specific super users. Denied any requests to use global permissions on specific surveys, because that's nonsense.
There's still some UI work to do to prevent people from attempting to put global permissions on surveys, but the backend will prevent it.
Try it out.
Trello: …
=> Global Permissions Handling

README.md, ui/src/SurveyDetails.js
When a user fixes bad CI rules, the new collex dialog doesn't reset the error, so the collex can't be created until the dialog is closed and reopened.
Reset the error flag when there's a backend error.
Enter bad CI rules and click to submit the new collection exercise, then fix the CI rules and click the button to submit the collex a second time... it should then work.
Trello: https://trello.com/c/OiC1uWuo
=> When incorrect CI rules are corrected error is reset

README.md, src/main/java/uk/gov/ons/ssdc/supporttool/schedule/FileStager.java, src/main/java/uk/gov/ons/ssdc/supporttool/schedule/RowStager.java
OpenCSV used to have a very good, useful, excellent and generally awesome API. Now it does not.
Changed to use the very bad API.
Zero regression.
Trello: https://trello.com/c/tSfAbCHV
=> Use CSVParserBuilder and CSVReaderBuilder instead of deprecated constructor

pom.xml, src/main/java/uk/gov/ons/ssdc/supporttool/utility/AllowTemplateOnSurveyValidator.java
We want to enable print fulfilment requests to supply extra personalisation values beyond what is stored on the case. The support tool template validation needs updating to allow these fields in the template when linking to a survey.
- Allow `__request__.` fields in template when linking to survey 
- Bump some minor dependency versions 
Build service branches, run the AT branch.
https://trello.com/c/fwLbkDJy/3209-ability-to-include-a-name-on-a-fulfilment-by-post-8
=> 3209 Print fulfilment request personalisation

src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/FulfilmentSurveyExportFileTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/messaging/PrintFulfilmentDTO.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/ui/ExportFileTemplateDto.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/ui/PrintFulfilment.java, src/main/java/uk/gov/ons/ssdc/supporttool/service/CaseService.java, ui/src/AllowedExportFileTemplatesOnFulfilmentsList.js, ui/src/PrintFulfilment.js, ui/src/Utils.js
Print fulfilments can now include extra personalisation values from the caller, where they are specified on the template. This PR adds form fields for these fields when they are found on the templates, so they can be sent from our UI.
- Update the export template API to return the full template object
- In the UI, when an export file template is selected for print fulfilment, check if it includes any request fields and add a form field set including inputs for each of these request values
- Update print fulfilment backend endpoint to pass through personalisation values
1. Checkout this branch, run `make build`
1. Spin up our local stack with docker dev
1. Set up a case for a survey and allow an export file template on said survey which includes at least one `__request__.` prefixed field …
=> 3245 Add request personalisation to print fulfilment request

src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ExportFileTemplateEndpoint.java, ui/src/ExportFileTemplatesList.js
We want to prevent users from being able to generate a print template that contains duplicate columns
Updated front and back end with validation for duplicates 
Should all still work as expected
https://trello.com/c/K5hPmnRb/3288-print-fulfilment-template-gives-internal-server-error-when-trying-to-add-a-template-with-duplicate-attributes-to-a-survey-5
=> 3288 - Prevent duplicate print template items in UI & backend

src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/AuthorisationEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/UserEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/UserGroupEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/UserGroupMemberEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/repository/UserGroupAdminRepository.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/repository/UserRepository.java, src/main/java/uk/gov/ons/ssdc/supporttool/security/UserIdentity.java, ui/src/UserAdmin.js
Could add same email twice, and lookup on email could fail if case different
Made case insensitive lookups
Can you add the same email twice, but with a different case letter? hopefully not.  
https://trello.com/c/IQ5b0zYl/3309-defect-adding-user-emails-in-support-tool-is-case-sensitive-5
=> update all email lookup to be case insensitive

src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/EmailTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/SmsTemplateEndpoint.java, ui/src/EmailTemplateList.js, ui/src/SmsTemplatesList.js
Stop users adding templates with duplicate columns
Checks for this in API and frontend.
Frontend should stop you creating an email or SMS with duplication.
To test the API you'll have to hack out the frontend code.
https://trello.com/c/ji0gpoDj/3335-support-tool-prevent-duplicate-columns-for-sms-email-templates-3
=> check for duplicate columns in templates email & sms

src/main/java/uk/gov/ons/ssdc/supporttool/utility/JobTypeHelper.java
PMD couldn't pass the JobTypeHelper class.
Presumed this was because it didn't like the fancy pant new Java 17 yielding switch statements.
I changed them to bog standard switch statements and the PMD issue has gone
Previously during 'make test' there was a PMD parsing error prior to the running of Tests.  
This should now be gone
& Zero regression
https://trello.com/c/Obm0f9Jq/3317-java-pmd-support-tool-warning-for-parsing-class-jobtypehelper-05-day
=> PMD wobbly fix

build.sh, pom.xml
The spotify dockerfile plugin has become out of date we've decided to remove it and use just a normal docker build after a mvn clean install
- Removed spotify dockerfile plugin
- Run `make build` and you should see it run mvn clean install and create a docker image with the jar afterwards
[Trello](https://trello.com/c/AHXXdTc5/)
=> Removed dockerfile plugin from pom file

src/main/java/uk/gov/ons/ssdc/supporttool/schedule/FileStager.java, src/main/java/uk/gov/ons/ssdc/supporttool/schedule/RowChunkStager.java, src/main/java/uk/gov/ons/ssdc/supporttool/schedule/RowStager.java, src/test/java/uk/gov/ons/ssdc/supporttool/schedule/FileStagerTest.java, src/test/java/uk/gov/ons/ssdc/supporttool/schedule/RowStagerTest.java, src/test/java/uk/gov/ons/ssdc/supporttool/testhelper/ScheduleHelper.java
Previously logged out exception message with sensitive data from file
Stops doing this, instead stores it against the job.  This is valid as data is already stored against the job, so the sensitive data is allowed to exist in that environment.
File attached to Ticket.  Build this branch.  make up in docker dev.   
Run "A simple email sample driven survey can be run in SRM" from ATs to get rules etc set up.
Then in your support tool locally http://localhost:9999/ navigate to the survey and collex.  
Then upload the 'bad_email_file.csv' from the ticket
https://trello.com/c/NgMahPqN/238-java-opencsv-puts-csv-data-in-exception-messages-1-day
=> Stop logging exception directly,  instead save message against Job

src/main/java/uk/gov/ons/ssdc/supporttool/config/WebSecurityConfig.java, src/test/java/uk/gov/ons/ssdc/supporttool/testhelper/IntegrationTestHelper.java, ui/public/index.html
We were getting chrome errors around the manifest used for static asset lookups. 
* Explicitly set the CDN manifest (same  as the ROps)
* Add trusted domain to `manifest-src` in CSP header
Run this in your GCP. Ensure the same error doesn't pop up when you inspect the console in your browser.
https://trello.com/c/tWLjQVOG
=> 256 Add explicit CDN for manifest link

src/main/resources/application.yml, ui/src/BulkUploads.js, ui/src/SampleUpload.js
The set limit on the server side support tool is 100mb,  make the UI respect this
check the size of the file being uploaded
Create some different file sizes and try them out
https://trello.com/c/wdsQgdxO/494-490mb-sample-file-in-support-tool-spike
=> 457 warn if file over 100mb

src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/SurveyCasesEndpoint.java, ui/src/SurveyCaseSearch.js
We want to add a limit so that its not possible for an excessive amount of cases to be returned in the search.
Limit of 100 added to the search api endpoint
Warning that shows up in front end if this limit is in place
make build
make up
create a survey that has enough cases in that when using a search term will return more than 100 of them
check that only 100 show up
check that you are warned you're not seeing all cases
https://trello.com/c/4nYKTnmj/499-add-safety-limit-to-support-tool-case-search-query-5
=> Add limits to case search

ui/src/SampleUpload.js
Previously you hit 'Process' and it could be 10 seconds before anything happened on screen 'have I hit it or not? doubts creep in'
Turns out it's easiest to stick a .then(()=>this.getjobs) on the end of it.  This makes it refresh once it's updated state - so it all works nicely,
Upload some files and check on/new version for speed difference
=> Quick process refresh

dummy-export-file-destination-config.json, src/test/java/uk/gov/ons/ssdc/supporttool/endpoint/AllEndpointsIT.java, src/test/java/uk/gov/ons/ssdc/supporttool/testhelper/IntegrationTestHelper.java
Because some pack code are set up automatically in the DDL and reference supplier names, we need the supplier names to be consistent across environments.
- Update dev supplier names
Build and run linked branches, run the ATs locally and or in a dev cloud env.
https://trello.com/c/1wjrYx5h/840-use-the-same-supplier-names-in-dev-as-prod
=> 840 Update dev suppplier config

src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/JobEndpoint.java
JobRows  with status `VALIDATED_ERROR` are never deleted from the job_row table, to enable the errors to be downloaded, however this causes a buildup of rows over time
Job rows are now deleted once both error CSVs have been downloaded.
- Load a sample with bad rows
- Process or cancel it
- Check that there are VALIDATED_ERROR rows in the job_row table
- Download one error CSV
- Check that the above rows are still present
- Download the other error CSV
- Check that the above rows are now gone
=> delete error job rows after download

ui/src/SurveySampleSearch.js
We need to guard against broad data retrieval when a user searches for all cases. This can be done by restricting to a collection exercise ID (primary key) in the search.
Updated the case search page
Make sure the case search still works as expected. You should now be prevented from searching without selecting a collection exercise ID
https://trello.com/c/DuRJxKbA
=> 995 Make Collection Exercise selection mandatory for Case Search

.github/dependabot.yml, ui/package-lock.json, ui/package.json
All dependabot PRs are currently blocked because they don’t include our mandatory versioning labels, which obscures which ones pass the tests without a deeper dive.
Added dependabot.yml file
Added labels to the dependabot config file
Check I've used the correct package ecosystem for the repo
Check the labels
https://trello.com/c/ZPLTDik6
=> 1234 dependabot patch label

build.sh, pom.xml
The maven plugin we use for docker compose on our java projects is no longer compatible and we concluded the best solution was to create a custom script to replace this.
Changed the original plugin to a custom one
Amended make command that skips docker compose 
Check it works locally on your machine
(https://trello.com/c/yOWPLr4O)
=> 1247 custom docker compose script

dummy-notify-config.json, pom.xml, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/EmailTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/NotifyServiceRefEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/SmsTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/ui/EmailTemplateDto.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/ui/SmsTemplateDto.java, src/main/resources/application.yml, src/test/java/uk/gov/ons/ssdc/supporttool/endpoint/AllEndpointsIT.java, src/test/java/uk/gov/ons/ssdc/supporttool/testhelper/IntegrationTestHelper.java, ui/src/EmailTemplateList.js, ui/src/SmsTemplatesList.js
At the moment the Gov Notify service we currently use has UKHSA branding on it which means we can't use it if we needed to onboard another survey. This PR adds the functionality to be able to supply multiple gov notify services by adding them to a json file which can be passed in.
-  Email templates and sms templates now show the service they're under
- When creating email templates and sms templates, you need to supply the gov notify service they are using 
- Run make build and all tests should pass
- Run with the other branches on the card and make sure it all works as expected
- Update the ddl with the ddl branch
- In support tool, create a email and sms template and try creating some with different services.
[Trello](https://trello.com/c/gL7KBQtj/)
=> 1043 govnotify create an additional service

ui/src/CollectionExerciseDetails.js
Currently the reschedule datetime is showing the same datetime twice when changing a action rule trigger datetime
- Show the updated datetime for the reschedule button
- Run the branch and set a action rule for the future. When rescheduling, you should be able to see both datetimes. 
[Trello](https://trello.com/c/biW1SiWy/)
=> Show correct reschedule action rule datetime

.github/dependabot.yml, ui/package-lock.json
We're getting overloaded with dependabot PRs so we needed a way to only get PRs for major updates
- Changed Config to only check for major version updates 
- Changed interval from Daily to Weekly 
Check it all looks ok
[Jira](https://jira.ons.gov.uk/browse/SDCSRM-385)
=> SDCSRM-385 Dependabot PRs for Security Only

ui/src/GroupDetails.js, ui/src/MyGroupUserAdmin.js
Currently there's no way of being certain which user you're removing from a group as the dialog popup doesn't say which it is
Added User's email address to the removal dialog popup for clarity
Try to remove a user
=> Added user email to confirm removal dialog

pom.xml, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ActionRuleEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/ui/ActionRuleDto.java, ui/src/CollectionExerciseDetails.js
It would be useful to be able to see how many cases each action rule has selected in the support tool UI
Added new column on each action rule to display the number of cases selected against it after it's triggered
Create a survey/CE/action rule in support tool and load a valid sample against it
Click the dry run button against the action rule and note how many cases should be picked up by that action rule
Wait for the rule to trigger and check that the number displayed against it in the 'Selected Cases' column is the same
=> Display number of selected cases against each triggered action rule

pom.xml, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ActionRuleEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/ui/ActionRuleDto.java, ui/src/App.js, ui/src/CollectionExerciseDetails.js
We need to set and display the new action rule status field on action rules.
- Add action rule status to action rule API
- Display the action rule status in the action rule details instead of `has_triggered`
Build the linked DDL branch, then the linked case processor branch, then this branch. 
Run docker dev
Run some action rules and watch the status change in the UI
https://jira.ons.gov.uk/browse/SDCSRM-520
=> SDCSRM-520 Productionise action rule status

ui/src/CollectionExerciseDetails.js, ui/src/index.css
We've noticed when rescheduling action rules that it's not displaying the correct times. It's expecting all the times to be bst so it's putting them back an hour which isn't what's reflected on the action rule table then. This is something we use in prod so it'll need to be fixed so it doesn't cause any confusion or problems
-  Updated the action rule trigger times to show in the timezone it's created in. So you'll see GMT for normal UTC times and GMT+01:00 for anything created in BST.
- Updated the rescheduling message so it now makes sense what you're updating
- Added IDs
- Run `make build` and bring up the branch with Docker-Dev
- Run the attached Acceptance Tests PR and make sure all the tests pass
- Run the Acceptance Tests in GCP to make sure the behaviour is what we expect it to be …
=> Sdcsrm 619 fix action rule datetime display

ui/src/BulkUploads.js, ui/src/CaseDetails.js, ui/src/CollectionExerciseDetails.js, ui/src/CollectionExerciseList.js, ui/src/ExceptionManager.js, ui/src/JobDetails.js, ui/src/SampleUpload.js, ui/src/Utils.js
Our dates are stored in UTC which can cause confusion when viewing things in the support tool UI during BST
changed all displayed dates to show in local time
create data and check all related pages to ensure dates are displayed with a timezone
=> Changed to localDateTimes throught the UI
