ONSdigital/ssdc-rm-support-tool

src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/JobEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/repository/JobRepository.java, src/main/java/uk/gov/ons/ssdc/supporttool/schedule/RowChunkStager.java, src/main/java/uk/gov/ons/ssdc/supporttool/schedule/RowStager.java, src/main/resources/application.yml, ui/package-lock.json, ui/src/CollectionExerciseDetails.js, ui/src/SampleUpload.js
There were bugs displaying sample upload progress etc.
Fixed the bugs. Improved some other stuff.
Try uploading a big sample file and watch the processing progress in the job details screen. Try uploading sample with errors in the CSV and try downloading the error details files.
Trello: https://trello.com/c/5ubCVnV9
=> Fix sample upload progress bugs and tidy up

pom.xml
Updated to point at new CI GCR
update image in pom to point at ssdc-rm-ci
=> updated to point at new CI GCR

src/test/resources/docker-compose.yml
Postgres 11 bad. Postgres 13 good.
11 -> 13
Build & check it still works.
Trello: https://trello.com/c/RoAn2AVn
=> Upgrade to Postgres 13

src/main/java/uk/gov/ons/ssdc/supporttool/model/entity/User.java
Hibernate DDL generation is not lining up perfectly.
Used explicit table naming for `users_surveys` table.
Build a GCP environment with the `apply.sh` script.
Trello: https://trello.com/c/4xu8QHn4
=> Fix DDL mapping pain

.codecov.yml, .travis.yml, src/test/java/uk/gov/ons/ssdc/supporttool/ReadValidationConfigTest.java
Travis is dead good.
Enabled Travis build again.
See if Travis is doing the do.
Trello: https://trello.com/c/s7n9mKb7
=> Re-enable Travis build

src/main/resources/application.yml, src/test/java/uk/gov/ons/ssdc/supporttool/ReadValidationConfigTest.java
rename queues
the sample queue name
mvn clean install
https://trello.com/b/yarvSxGu/census-2021-response-management
=> change sample queue

ui/src/CaseDetails.js
Events can be linked to either a case, or a UAC. We currently aren't displaying the events linked to UACs.
Display the events which aren't linked to cases, but are linked to a UAC (e.g. authenticated, launched, receipted, UAC deactivated etc)
Chuck in an event of the forbidden kind (e.g. authenticated, launched, receipted, UAC deactivated etc) and check that they're visible on the case details screen.
Trello: https://trello.com/c/bPi9g4CI
=> Display events linked to UAC QIDs

src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/DeactivateUacEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/service/CaseService.java, src/main/java/uk/gov/ons/ssdc/supporttool/utility/EventHelper.java, src/test/java/uk/gov/ons/ssdc/supporttool/utility/EventHelperTest.java
Need to have consistent naming on our events
* Use `EventHelper` like in the other repos from this ticket
Run the tests, make sure they still pass
https://trello.com/c/u1GEyNYO/2508-what-the-heck-is-the-caseservice
=> 2508 consistent event naming

src/main/java/uk/gov/ons/ssdc/supporttool/config/WebMvcConfig.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/Authorisation.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/CaseEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/DeactivateUacEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/FileUploadEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/JobEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/PrintSuppliers.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/SurveyCasesEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/WhoAmI.java, src/main/java/uk/gov/ons/ssdc/supporttool/security/UserIdentity.java, src/main/java/uk/gov/ons/ssdc/supporttool/security/UserIdentityInterceptor.java
When uploading massive sample files (e.g. hundreds of Mb) the backend checks the JWT token after the upload has finished... and it's expired.
Check the JWT token up front, using a Spring interceptor.
Upload a massive sample file to a GCP environment.
Trello: https://trello.com/c/ZO5wZguE
=> Improve handling of Google IAP header JWT token

src/main/java/uk/gov/ons/ssdc/supporttool/config/WebMvcConfig.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/Authorisation.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/CaseEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/DeactivateUacEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/FileUploadEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/JobEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/PrintSuppliers.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/RefusalsEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/SurveyCasesEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/UiRedirectController.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/WhoAmI.java, src/main/java/uk/gov/ons/ssdc/supporttool/security/UserIdentity.java, src/main/java/uk/gov/ons/ssdc/supporttool/security/UserIdentityInterceptor.java, src/main/resources/application.yml, ui/src/CaseDetails.js, ui/src/CollectionExerciseDetails.js, ui/src/InvalidAddress.js, ui/src/LandingPage.js, ui/src/PrintFulfilment.js, ui/src/Refusal.js, ui/src/SampleUpload.js, ui/src/SurveyCaseSearch.js, ui/src/SurveyDetails.js, ui/src/SurveySampleSearch.js, ui/src/SurveySimpleSearchInput.js, ui/src/Utils.js
Reloading the page doesn't work because Spring intercepts the get request and gives a 404.
Moved all endpoints to `/api` and forwarded any request for anything else back to the root.
Navigate around and try the refresh button.
Trello: https://trello.com/c/FMznyeqK
=> Fix reload bug due to spring routing

ui/src/CollectionExerciseDetails.js, ui/src/LandingPage.js, ui/src/SampleUpload.js, ui/src/SurveyCaseSearch.js, ui/src/SurveyDetails.js
Not all the features had RBAC.
Added RBAC on every feature in the UI.
Try switching your user in docker dev by changing `DUMMY_USER` in the `.env` file.
Trello: https://trello.com/c/GueiShpS
=> Lock down remaining features using RBAC

pom.xml, src/test/java/uk/gov/ons/ssdc/supporttool/ReadValidationConfigTest.java, src/test/java/uk/gov/ons/ssdc/supporttool/utility/EventHelperTest.java
Need to migrate Case API, Exception Manager, UAC QID Service and Support Tool to JUnit 5
Updated pom.xml
Updated tests
Build run to check nothing breaks
Run make build
https://trello.com/c/VYaJVu9x
https://www.baeldung.com/junit-5-migration
=> JUnit 5 Migration

pom.xml
Spring boot v2.5.3 is now available so it's time to upgrade it
- Upgraded to spring boot v2.5.3
- Removed not needed dependencies in the pom.xml
- Run make build
- Run with docker dev and run the ATs to make sure they pass
[Trello](https://trello.com/c/kUeel0Da/)
=> Upgrade spring boot to 2.5.3

src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/CaseEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/DeactivateUacEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/messaging/EventDTO.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/entity/Event.java, src/main/java/uk/gov/ons/ssdc/supporttool/service/CaseService.java, src/main/java/uk/gov/ons/ssdc/supporttool/utility/EventHelper.java, src/test/java/uk/gov/ons/ssdc/supporttool/utility/EventHelperTest.java
We want to be able to keep an audit trail of all the users that make actions against a case in the support tool
- User is passed into event to be set as createdBy
- Run with the case processor branch on the trello ticket
- create a survey/collex and upload a sample
- Create some refusals/ invalid addresses/ fulfilments/deactivate uacs in the support tool for the case and the user should be specified in the Events table in the DB
[Trello](https://trello.com/c/qfJKp8m3)
=> Pass user email to events

ui/src/SurveyDetails.js
It's useful to see which survey you're viewing.
Added survey name.
Try it.
Trello: https://trello.com/c/6Nuo7nVv
=> Display survey name

src/main/resources/application.yml
This: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/494
Fixed.
Ugh.
Trello: https://trello.com/c/AIOvIqVM
=> Disable pubsub healthcheck because it requires extra topic security

src/main/java/uk/gov/ons/ssdc/supporttool/client/ExceptionManagerClient.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ExceptionManager.java, src/main/resources/application.yml, ui/src/App.js, ui/src/ExceptionManager.js, ui/src/LandingPage.js
Wouldn't it be nice if there was a UI to manage exceptions, rather than having to use the toolbox "Bad Rabbit Message wizard"?
Created a UI for exception manager.
Try it.
Trello: https://trello.com/c/4JEbEbWB
=> Manage exceptions

ui/src/CaseDetails.js
This:
Fixed it.
Test it.
Trello: https://trello.com/c/JhtQFWsX
=> Fix invalid status on case details screen

pom.xml
Bump common entity models version
- Bump common entity models version
Not required
https://trello.com/c/Lni8psPO/2691-productionise-database-based-print-file-building-spike-8
=> 2691 Bump common entity models version

src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/SurveyCasesEndpoint.java
Search by caseref and QID were broken.
Fixed.
Try it.
Trello: https://trello.com/c/sfJtAbQu
=> Fix search by caseref and QID

pom.xml
It's a pain when we're making model changes, because we have to build case processor before the integration tests start passing in the other projects: Case API, Notify Service & Response Operations.
Also, having to remember to generate DDL changes in a different repo, when the model has been changed, is something that's easily forgotten/overlooked.
Combined the DDL and common entities repos. Built a Postgres image which we can use in all the repos that use the common data model.
Run the integration tests in all the projects... should still work.
Trello: https://trello.com/c/EBa69kMx
=> Combine DDL and entities into one repo to rule them all

src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/SurveyCasesEndpoint.java
Searching for invalid cases causes "undefined" alert popup.
Fixed it.
Search for invalid cases.
Trello: https://trello.com/c/jbldjvAo
=> Fix invalid case search

src/main/java/uk/gov/ons/ssdc/supporttool/utility/Constants.java
Bump JSON schema version to latest
JSON schema version bump
Run the acceptance tests
https://trello.com/c/OcShPvHZ/2873-move-to-json-schema-v03-release-3
=> 2873 - Update JSON schema version

ui/src/ExceptionManager.js
Exception manager had stopped working.
Fixed bug.
Create an exception and check you can see it.
Trello: https://trello.com/c/zNYUsQQ4
=> Fix exception manager screen permission check

ui/src/CaseDetails.js, ui/src/CollectionExerciseDetails.js
The order that things are displaying in the UI is not consistent.
Sorted the UAC QID and Action Rule tables.
Try it!
Trello: https://trello.com/c/FPRmy8gI
=> Sort UAC QIDs and Action Rules

ui/src/BulkUploads.js
The back end now a handles these job types, so we can add them to our bulk processing UI.
- Add bulk processing history tables and upload functionality for bulk invalid, update sample, and update sample sensitive
Build and run locally, try uploading each new type through the UI.
https://trello.com/c/iXz15pgH/2979-bulk-processor-sample-sensitive-and-sample-updates-and-invalid-front-end-5
=> 2979 Add bulk invalid, update sample, and update sample sensitive

pom.xml
Bump common entities.
Bump.
Zero regression.
Trello: https://trello.com/c/Rwv4wxTa
=> Bump common entities

src/main/java/uk/gov/ons/ssdc/supporttool/schedule/RowChunkValidator.java
We aren't able to blank out sensitive (PII) data when using the bulk processing features.
Ignore validation rules if the data is being blanked out.
Try blanking out some sensitive data in a bulk file.
Trello: https://trello.com/c/nt2nJ9d2
=> Do not validate sensitive data when bulk blanking

src/main/java/uk/gov/ons/ssdc/supporttool/config/AppConfig.java, src/main/resources/application.yml, src/main/resources/logback.xml
Nicer logging
Locally with docker dev, check nothing broken, logs look similar to before
In GCP with K8s branch.  
https://trello.com/c/CaG0Bhuj/3054-use-structured-logging-in-all-our-java-services-3
=> Add logback

pom.xml, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/UserGroupEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/UserGroupMemberEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/ui/UserGroupDto.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/ui/UserGroupMemberDto.java, src/test/java/uk/gov/ons/ssdc/supporttool/endpoint/AllEndpointsIT.java, ui/src/GroupDetails.js, ui/src/MyGroupUserAdmin.js, ui/src/MyGroupsAdmin.js, ui/src/UserAdmin.js, ui/src/UserDetails.js
With only the name of a user group, it's hard to know what the purpose of a group is: who is it for and what permissions does it give? What role is it for?
Added description to user groups.
Have a play around with it in the support tool UI.
Trello: https://trello.com/c/Dh3YAyND
=> Add user group description

src/main/java/uk/gov/ons/ssdc/supporttool/config/AppConfig.java
new fangled json logging broke local logging
Make the json log conditional on profile
Make it log and check the output is there for log with style messages
https://trello.com/c/B4tUlG3N/3090-fix-local-logging-3
=> fix local logging

src/main/java/uk/gov/ons/ssdc/supporttool/config/AppConfig.java
=> logging profile fix

pom.xml
=> log4j bump

Makefile, build.sh, ui/.eslintrc.json, ui/package-lock.json, ui/package.json, ui/src/App.test.js, ui/src/ExceptionManager.js
Add ESLint to improve code  - 1st stab at getting it in, and small tidy ups:  have added https://trello.com/c/HwoJIE4D/3174-tech-session-discussion-on-react-styles   for a discussion about styles, exclusions et
Add ESLint
Do some bad code, leave an unused Var around and see what happend
https://trello.com/c/UtDs9a3k/3143-reactjs-keep-it-tidy-peeps-5
=> Add eslint tidy up

pom.xml, ui/package-lock.json
=> bump common

pom.xml, ui/package-lock.json
We need a new refusal type for anyone whos previously agreed to take part in a survey but now wants to withdraw. We also need functionality to remove sensitive data if a respondent asks us to remove their data.
- update common entity version
- Run with other branches and run the ATs
- Refuse a case and pass in `eraseData = true` and make sure the sensitive data in the event is removed
[Trello](https://trello.com/c/q8cx1tZn/)
=> Update common entity version

exclude-pmd.properties, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/CollectionExerciseEndpoint.java
PMD check has identified a few classes which don't make full use of passing exception details through.
Fixed exception handling recommended by PMD check
Ensure it still builds 
https://trello.com/c/Zmm62ErR
=> 3308 Fix PMD PreserveStackTrace Warning

pom.xml
=> bumped versions

src/main/java/uk/gov/ons/ssdc/supporttool/security/UserIdentityInterceptor.java
We need a basic level of audit logging on support tool use, this PR achieves that by adding a post request hook which logs the request routes, results and calling user
- Add audit logging post request hook
Build and run this branch locally, try using the support tool and checking the logs, you should see the API activity. Note that some UI pages will be quite noisy in the logs, this is expected until/unless we tidy up how the front end is making it's calls.
https://trello.com/c/5oneBBRm/165-support-tool-audit-logging-3
=> 165 Add API Audit logging

src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ActionRuleEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ActionRuleSurveyEmailTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ActionRuleSurveyExportFileTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ActionRuleSurveySmsTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/AuthorisationEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/CaseEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/CollectionExerciseEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/DeactivateUacEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/EmailTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ExportFileTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/FulfilmentNextTriggerEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/FulfilmentSurveyEmailTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/FulfilmentSurveyExportFileTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/FulfilmentSurveySmsTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/JobEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/SmsTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/SurveyCasesEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/SurveyEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/UserEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/UserGroupAdminEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/UserGroupEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/UserGroupMemberEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/UserGroupPermissionEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/security/UserIdentity.java, src/main/java/uk/gov/ons/ssdc/supporttool/utility/CaseSearchResultsMapper.java
Many errors in the support tool backend don't log anything
Added logging for all exceptions that didn't log anything useful
=> 162 support tool improve backend error logging

src/main/java/uk/gov/ons/ssdc/supporttool/config/WebSecurityConfig.java, src/test/java/uk/gov/ons/ssdc/supporttool/testhelper/IntegrationTestHelper.java
We're missing a security header that needs to be set
- Added permissions policy to web security config
Run make test and the ATs
[Trello](https://trello.com/c/dp3blNNI/)
=> Added permissions-policy to websecurityconfig

pom.xml
Whilst looking at POM for a ticket saw there was some unneeded dependences in the pom
Removed unused Poms dependencies
Run 'make test'
=> remove 2 unused dependencies from POM

src/main/java/uk/gov/ons/ssdc/supporttool/config/WebSecurityConfig.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/SurveyEndpoint.java, src/main/resources/application.yml, ui/src/AllowedEmailTemplatesOnActionRulesList.js, ui/src/AllowedExportFileTemplatesActionRulesList.js, ui/src/CollectionExerciseDetails.js, ui/src/CollectionExerciseList.js, ui/src/EmailTemplateList.js, ui/src/ExportFileTemplatesList.js, ui/src/JobDetails.js, ui/src/LandingPage.js, ui/src/SampleUpload.js, ui/src/SurveysList.js
We've added UI tests to the AT repo and we've had to IDs to the elements around support tool so chromedriver can navigate around the page.
An issue came out with the `upgrade-insecure-requests;` CSP policy redirecting network requests over https. This was causing the tests to fail as the chromedriver couldn't access the elements on support tool so we've had to make it an env var so we can make it an empty string in dev projects
- Added IDs around the page
- Made `upgrade-insecure-requests;` a env var in the application.yml
Run with the ATs branch locally and in a gcp project to check all works.
[Trello](https://trello.com/c/FvlixjUv/)
=> 164 support tool tests key features only

pom.xml, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/CollectionExerciseEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/messaging/CollectionExerciseUpdateDTO.java, src/test/java/uk/gov/ons/ssdc/supporttool/endpoint/AllEndpointsIT.java, src/test/java/uk/gov/ons/ssdc/supporttool/endpoint/CollectionExerciseEndpointIT.java, src/test/java/uk/gov/ons/ssdc/supporttool/endpoint/CollectionExerciseEndpointTest.java, src/test/java/uk/gov/ons/ssdc/supporttool/testhelper/IntegrationTestHelper.java
work with new collexIntrumentRule
with others from ticket
https://trello.com/c/jxMboyx6/549-send-metadata-from-sample-data-to-eq-for-routing-piping-and-linking-13
=> 549 send metadata from sample data to eq for routing piping and linking

pom.xml, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ActionRuleEndpoint.java, src/test/java/uk/gov/ons/ssdc/supporttool/endpoint/AllEndpointsIT.java, ui/src/CollectionExerciseDetails.js
Add support for EQ Flush action types
- Add support for EQ Flush action types
- Bump common entities
Build and run all the branches locally, run the ATs branch. Try creating/running an EQ Flush action rule from support tool.
https://trello.com/c/sN2EG6Rh/621-eq-flushing-by-action-rule-with-rate-limiting-13
=> 621 Bump common entities

src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/resources/application-test.yml
To get the tests passing again, the config needs to be tweaked so it points at the renamed db `rm`
Updated testing and local config
Make sure the tests pass
https://trello.com/c/PDs8417G
=> 776 Update config to get tests passing

ui/package-lock.json
This PR groups together the recent dependabot PRs which bumped various dependencies used by our support tool
Bumped dependencies
Test some of the core functionality in the Support Tool UI - does it still work?
https://trello.com/c/PDs8417G
=> 776 Bump dependencies

ui/package-lock.json
Update dependencies
Updated the non-breaking change dependencies.  The changes address both dependabot PRs.
All tests should pass and everything should work as normal
https://github.com/ONSdigital/ssdc-rm-support-tool/pull/250
https://github.com/ONSdigital/ssdc-rm-support-tool/pull/251
https://trello.com/c/v77XGnEP
=> Update node packages

src/test/java/uk/gov/ons/ssdc/supporttool/endpoint/SurveyEndpointIT.java, src/test/resources/setup_pubsub.sh
We've removed the unused `event_survey-update_rh` subscription so I've renamed the name of the subscription listening to the case_update topic in the integration tests to avoid confusion
=> Cleanout unused pubsub stuff 

src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/CaseEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/CollectionExerciseEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/ui/CaseDto.java, ui/src/App.js, ui/src/CaseDetails.js, ui/src/CollectionExerciseDetails.js, ui/src/CollectionExerciseList.js, ui/src/SurveyDetails.js
There have been a few data improvement suggestions made for the support tool to help with daily use.
* Added survey details Survey page
* Added extra collection exercise details to Survey page
* Added non-sensitive sample data to Case details page
* Clicking the support tool text at top of page now returns to landing page
Spin it up and check the above works okay
https://trello.com/c/o637BlHJ
=> 699 Small improvements to data views etc

.github/workflows/checks-and-tests.yml, src/main/java/uk/gov/ons/ssdc/supporttool/client/ExceptionManagerClient.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ExceptionManagerEndpoint.java, src/main/resources/application.yml, src/test/java/uk/gov/ons/ssdc/supporttool/endpoint/ExceptionManagerEndpointIT.java, src/test/resources/application-test.yml, ui/package-lock.json, ui/src/AllowedEmailTemplatesOnActionRulesList.js, ui/src/AllowedEmailTemplatesOnFulfilments.js, ui/src/AllowedExportFileTemplatesActionRulesList.js, ui/src/AllowedExportFileTemplatesOnFulfilmentsList.js, ui/src/AllowedSMSTemplatesActionRulesList.js, ui/src/AllowedSMSTemplatesOnFulfilmentsList.js, ui/src/ExceptionManager.js
The support tool exception manager page struggles to load too many messages and becomes unusable with high amounts
Added a count for bad message and stop displaying them if over a certain amount 
Keep creating bad messages, see that the count goes up and that the messages stop being displayed once above the threshold
=> Added bad message count to UI

.github/dependabot.yml, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ActionRuleEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/model/dto/ui/ActionRuleDto.java, src/test/java/uk/gov/ons/ssdc/supporttool/endpoint/AllEndpointsIT.java, src/test/java/uk/gov/ons/ssdc/supporttool/testhelper/BundleOfUsefulTestStuff.java, src/test/java/uk/gov/ons/ssdc/supporttool/testhelper/IntegrationTestHelper.java, ui/package-lock.json, ui/package.json, ui/src/CollectionExerciseDetails.js
An easier way to reschedule action rules would make our lives easier
UI:
- Added an extra button in support tools when looking at actions
- Button will open a dialog where you can input the new date and time
- A confirm box will open to double check you wish to change the time
Endpoint:
- Added a 'put' method in the support tool back end point to update trigger time
Added a test case
Run the code locally in docker dev and see if it updates the trigger time
Check the UI is intuitive 
https://trello.com/c/Y9s01znI
=> 983 reschedule action Rules

ui/package-lock.json, ui/package.json
One of the sub-dependencies for a few packages had a high vulnerability - see the comment on the Trello card for more details.
Added the [npm dependency resolution override mechanism](https://github.com/npm/rfcs/blob/main/accepted/0036-overrides.md) for the sub dependency
Make sure it builds ok
https://trello.com/c/ssbPhHPG/1249-fix-react-npm-vulnerabilites-5
=> Fix npm vulnerabilites

package-lock.json, ui/package-lock.json, ui/package.json, ui/src/App.js
We wanted to update react-router-dom, but it required some changes to the code.
The ```switch``` for routing from react-router-dom has been changed to ```routes``` which required changing some of the syntax.
Build the project and make up in docker dev.
Run the ATs
Check that the UI works in your browser correctly
Check in your GCP env if you fancy?
https://jira.ons.gov.uk/browse/SDCSRM-357
=> Update react router dom and change switch to routes

pom.xml, ui/package-lock.json, ui/package.json
There's a bunch of dependabot PRs that need to be addressed. I've put some onto a single PR to fully test it as some were failing silently.
- Updated the dependencies
- Run make build and run with the ATs to make sure it all passes
[Jira](https://jira.ons.gov.uk/browse/SDCSRM-463)
=> Updating dependabot dependencies

pom.xml, src/test/java/uk/gov/ons/ssdc/supporttool/testhelper/IntegrationTestHelper.java
The common entities have been updated.
- Bump the common entities version
No functional change, the tests should pass once the DDL repo change has been merged and the new artifact built.
https://jira.ons.gov.uk/browse/SDCSRM-577
=> SDCSRM-577 Bump common entities version

src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ActionRuleEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ActionRuleSurveyEmailTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ActionRuleSurveyExportFileTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/ActionRuleSurveySmsTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/CollectionExerciseEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/DeactivateUacEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/FulfilmentSurveyEmailTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/FulfilmentSurveyExportFileTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/FulfilmentSurveySmsTemplateEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/SurveyEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/security/IAPUser.java, src/test/java/uk/gov/ons/ssdc/supporttool/security/IAPUserTest.java
Changed so that it always asks for permission before it allows users to get information
Run Acceptance test and manually check
=> changed permissions

src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/CollectionExerciseEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/DeactivateUacEndpoint.java, src/main/java/uk/gov/ons/ssdc/supporttool/service/CaseService.java, src/main/java/uk/gov/ons/ssdc/supporttool/service/SurveyService.java, src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/java/uk/gov/ons/ssdc/supporttool/endpoint/CollectionExerciseEndpointIT.java, src/test/java/uk/gov/ons/ssdc/supporttool/endpoint/SurveyEndpointIT.java, src/test/java/uk/gov/ons/ssdc/supporttool/testhelper/PubsubHelper.java, src/test/resources/application-test.yml, src/test/resources/setup_pubsub.sh
We no longer need to use a shared pubsub project
References to the shared pubsub project removed and relevant thing renamed
Build and test along with all the other PRs that are to do with removing and renaming references to the shared pubsub project.
https://jira.ons.gov.uk/browse/SDCSRM-538
=> Remove references to shared pubsub project

ui/package-lock.json, ui/package.json
There was an open dependabot warning due to a vulnerable dependency
Updated dependencies
Run acceptance tests and click round the UI
=> Upgraded dependency versions

pom.xml
Common entity needed to be bumped
Bumped common entity
Build DDL changes
add -SNAPSHOT to the end of the version
run `make build`
https://officefornationalstatistics.atlassian.net/browse/SDCSRM-1071
=> SDCSRM-1071 Bump common entity
